### ISSUE TITLE
Release trained models as well.

### ISSUE THREAD

**Issue by sumandroid12** [scaleway/frontalization#1]

**Comment by wait1988** [comment]
Will you release the pretrained model for a quick test?

**Comment by opetrova** [comment]
Sorry for the delay, here you go: https://github.com/scaleway/frontalization/tree/master/pretrained 
There are some issues with this `v0` release, as I explain in the Readme, but one could still use it for testing and/or transfer learning purposes. I am training a couple more models with different GAN regimes right now, so might update this later if the new versions generalise better.

**Comment by bleakie** [comment]
I tested the effect of the model and found that it was not ideal. The similarity between the generated face and the original image was very small. How to solve it?

**Comment by opetrova** [comment]
> I tested the effect of the model and found that it was not ideal. The similarity between the generated face and the original image was very small. How to solve it?

Did you use the same normalization as in the code and do a close crop of the face?
